### ISSUE TITLE
Errors In IntelliJ

### ISSUE THREAD

**Issue by SalamiSandwich0** [tpollard64/Nvidia-RTX-Hero#1]
![image](https://user-images.githubusercontent.com/20758581/95549098-2d204500-09cc-11eb-81b2-0ee3abe85a6c.png)
Followed the instructions but there are errors in intelliJ I believe they have to do with chromium and selenium

**Comment by tpollard64** [comment]
Download [Chromium](https://www.chromium.org/getting-involved/download-chromium) and unzip the .exe in the NVIDIA-RTX-HERO folder. 

Please let me know if that works so I can close this issue.

**Comment by tpollard64** [comment]
Also after looking at this again, it looks like the .jars for selenium were not properly imported. There should be two-three jars in the top-level selenium folder that you need to imports, as well as all the jars in the /bin folder.

**Comment by SalamiSandwich0** [comment]
![image](https://user-images.githubusercontent.com/20758581/95623401-cf771180-0a3a-11eb-9023-4e8bc93d1d2a.png)
Oh thanks that was able to resolve most of the errors. Afterwards, I'm supposed to run it right? it gave me a webdriver error, am I supposed to map something?

**Comment by SalamiSandwich0** [comment]
should i try this?: System.setProperty("webdriver.chrome.driver", "E:\\chromedriver.exe");

**Comment by tpollard64** [comment]
Put the chromium .exe that you downloaded in the top level rtx-hero folder. That's all you need.

**Comment by SalamiSandwich0** [comment]
I did, that didnt work
