### ISSUE TITLE
Cannot find symbol method setHeadless(boolean)

### ISSUE THREAD

**Issue by ankhmpt** [tpollard64/Nvidia-RTX-Hero#2]
Hello,
 I'm getting the following error.
cannot find symbol method setHeadless(boolean)

<img width="1094" alt="123" src="https://user-images.githubusercontent.com/32017643/95606660-418e2d00-0a20-11eb-8a75-a0ee97550b87.png">

**Comment by tpollard64** [comment]
I believe there is something wrong with your imports. Can you screenshot the imports at the top of the main.java?

**Comment by ankhmpt** [comment]
I re-downloaded Nvidia-RTX-Hero and its working.

**Comment by tpollard64** [comment]
Glad to hear!
