### ISSUE TITLE
Exception even with chromium in root Hero directory

### ISSUE THREAD

**Issue by SalamiSandwich0** [tpollard64/Nvidia-RTX-Hero#3]
![image](https://user-images.githubusercontent.com/20758581/95636561-16720080-0a55-11eb-8846-cb033cdd70b4.png)
I put the exe file in the root of the hero folder as you mentioned but it did not work. I tried putting the entirety of the chromium files in the same area but that also did not work

**Comment by SalamiSandwich0** [comment]
![image](https://user-images.githubusercontent.com/20758581/95637014-466dd380-0a56-11eb-9f49-a790a6ba7cab.png)
I tried downloading the chromedriver.exe and putting it in the folder too but that just yielded a different yet longer error

**Comment by tpollard64** [comment]
Try removing chrome from that file.

**Comment by SalamiSandwich0** [comment]
Here is the error with chrome.exe removed 
![image](https://user-images.githubusercontent.com/20758581/95641884-95256880-0a6a-11eb-980a-8327d0abae4d.png)

**Comment by SalamiSandwich0** [comment]
looks to be the same

**Comment by SalamUchiha** [comment]
Don't you have a zipped folder of this project? Wouldn't it be a lot easier if I extracted and ran that instead?

**Comment by SalamiSandwich0** [comment]
Nevermind, everything is working now. Thank you
